name: Notify Discord on PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      USER: ${{ github.actor }}
      URL: ${{ github.event.pull_request.html_url }}
      MERGED: ${{ github.event.pull_request.merged }}
    steps:
      - name: Debug variáveis
        run: |
          echo "REPO=$REPO"
          echo "USER=$USER"
          echo "URL=$URL"
          echo "MERGED=$MERGED"

      - name: Enviar mensagem para o Discord se merged
        if: env.MERGED == 'true'
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "GitHub Bot",
              "content": "**Novo merge no projeto:** '"$REPO"'\n**Nome do Usuário:** '"$USER"'\n**Data:** '"$(date '+%d/%m/%Y %H:%M')"'\n**Veja aqui:** '"$URL"'
            }' \
            https://discord.com/api/webhooks/SEU_WEBHOOK_AQUI
